### PR TITLE
Return runtime error for invalid length constraint values

### LINKED ISSUE #3580: Constraint compiler plugin fails when value is provided through a variable
**Description:**

> $Subject

**Steps to reproduce:**

Run the following code :
```ballerina
import ballerina/constraint;

int a = 5;

@constraint:String {
     length: a
}
type TestString string;
```

```console
$ bal run

Compiling source
        user/pattern_constraint_tests:0.1.0
error: compilation failed: The compiler extension in package 'ballerina:constraint:1.0.1' failed to 
complete. For input string: "a"
```

**Affected Versions:**

Ballerina SwanLake `2201.2.2`

**OS, DB, other environment details and versions:**

MacOS

### PR DESCRIPTION
**Pull request by TharmiganK**
## Purpose

> $Subject

> Also Fixes : [`Constraint compiler plugin fails when value is provided through a variable #3580`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3580)

## Examples

```ballerina
import ballerina/constraint;
import ballerina/log;

int a = -5;

@constraint:String {
    length: a
}
type StringA string;

public function main() {
    StringA stringA = "s3cr3t";
    StringA|error validation = constraint:validate(stringA);
    if validation is error {
        log:printError("error occurred while validating stringA", validation);
    } 
}
```

```console
$ bal run

Compiling source
        user/pattern_constraint_tests:0.1.0

Running executable

time = 2022-11-03T12:25:49.328+05:30 level = ERROR module = user/pattern_constraint_tests 
message = "error occurred while validating string A" 
error = "invalid value found for $:length constraint. Length constraints should be positive"
```

## Checklist
- [x] Linked to an issue
- [x] Updated the changelog
- [x] Added tests
- [ ] <s>Updated the spec</s>
- [x] Checked native-image compatibility

### CODE REVIEW

File: native/src/main/java/io/ballerina/stdlib/constraint/validators/AbstractLengthValidator.java [hunk 1]
```diff
@@ -38,7 +39,9 @@ public void validate(BMap<BString, Object> constraints, Object fieldValue, List<
                          String path) {
         for (Map.Entry<BString, Object> constraint : constraints.entrySet()) {
             long constraintValue = (long) constraint.getValue();
-            switch (constraint.getKey().getValue()) {
+            String constraintFiled = constraint.getKey().getValue();
```
Comment (chamil321) [inline native/src/main/java/io/ballerina/stdlib/constraint/validators/AbstractLengthValidator.java]:
```suggestion
            String constraintField = constraint.getKey().getValue();
```

Comment (TharmiganK) [reply native/src/main/java/io/ballerina/stdlib/constraint/validators/AbstractLengthValidator.java]: Fixed via [38dfb93](https://github.com/ballerina-platform/module-ballerina-constraint/pull/30/commits/38dfb93445ff8b2b3ceefb680b9eb9c1e650c33e)

**Review by chamil321 — APPROVED** [review]
